[package]
name = "proxmox-mail-forward"
version = "0.1.1"
authors = [
    "Fiona Ebner <f.ebner@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
description = "Proxmox mail forward helper"
homepage = "https://www.proxmox.com"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
log = "0.4.17"
nix = "0.26"
serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"
syslog = "4.0"

proxmox-schema = "1.3.4"
proxmox-section-config = "1.0.2"
proxmox-sys = "0.4"
